// 365 Swami Samarth Quotes - Marathi and English
const SWAMI_QUOTES = [
  { mr: "भय नाही तुला, स्वामी पाठीशी आहे.", en: "Fear not, Swami is with you." },
  { mr: "श्रद्धा ठेव, स्वामी सर्व सांभाळतील.", en: "Have faith, Swami will take care of everything." },
  { mr: "नाम घे, नाम तुला तारेल.", en: "Chant the name, the name will uplift you." },
  { mr: "स्वामी समर्थ हेच तुझे रक्षण.", en: "Swami Samarth is your protection." },
  { mr: "भक्तीने सर्व शक्य आहे.", en: "Everything is possible through devotion." },
  { mr: "जे होते ते चांगल्यासाठीच होते.", en: "Whatever happens, happens for the good." },
  { mr: "स्वामी कृपा सदैव तुझ्यावर आहे.", en: "Swami's grace is always upon you." },
  { mr: "धीर धर, स्वामी तुझ्याबरोबर आहेत.", en: "Be patient, Swami is with you." },
  { mr: "नामस्मरण हेच खरे साधन.", en: "Chanting the name is the true practice." },
  { mr: "स्वामींचे नाव हेच तारक मंत्र.", en: "Swami's name is the saving mantra." },
  { mr: "विश्वास ठेव, मार्ग दिसेल.", en: "Keep faith, the path will appear." },
  { mr: "स्वामी समर्थांची कृपा अनंत आहे.", en: "Swami Samarth's grace is infinite." },
  { mr: "तुझ्या प्रत्येक श्वासात स्वामी आहेत.", en: "Swami is in your every breath." },
  { mr: "भक्ती हीच खरी संपत्ती.", en: "Devotion is the true wealth." },
  { mr: "स्वामींचा आशीर्वाद तुझ्यावर सदैव आहे.", en: "Swami's blessings are always upon you." },
  { mr: "नामजप करणाऱ्यास कशाचीही चिंता नाही.", en: "One who chants has no worries." },
  { mr: "स्वामी तुझ्या कष्टांची जाणीव आहे.", en: "Swami is aware of your hardships." },
  { mr: "शरणागती हेच खरे बळ.", en: "Surrender is the true strength." },
  { mr: "स्वामींच्या चरणी सर्व अर्पण कर.", en: "Offer everything at Swami's feet." },
  { mr: "तू एकटा नाहीस, स्वामी तुझ्याबरोबर.", en: "You are not alone, Swami is with you." },
  { mr: "प्रत्येक दिवस स्वामींची देणगी.", en: "Every day is a gift from Swami." },
  { mr: "स्वामींचे स्मरण हेच ध्यान.", en: "Remembering Swami is true meditation." },
  { mr: "कर्म कर, फळ स्वामींवर सोड.", en: "Do your work, leave the results to Swami." },
  { mr: "स्वामी तुला कधीही सोडणार नाहीत.", en: "Swami will never abandon you." },
  { mr: "तुझी प्रार्थना स्वामींपर्यंत पोहोचते.", en: "Your prayers reach Swami." },
  { mr: "नम्रता हीच खरी भक्ती.", en: "Humility is true devotion." },
  { mr: "स्वामी कृपेने सर्व अडथळे दूर होतात.", en: "By Swami's grace, all obstacles are removed." },
  { mr: "तुझे जप व्यर्थ जात नाहीत.", en: "Your chanting never goes in vain." },
  { mr: "स्वामी तुझ्या हृदयात वास करतात.", en: "Swami dwells in your heart." },
  { mr: "प्रेमाने नाम घे, स्वामी प्रसन्न होतील.", en: "Chant with love, Swami will be pleased." },
  { mr: "स्वामी समर्थ — हाच तारक मंत्र.", en: "Swami Samarth — this is the saving mantra." },
  { mr: "सत्कर्माला स्वामींचा आशीर्वाद मिळतो.", en: "Good deeds receive Swami's blessings." },
  { mr: "स्वामींच्या नामात अद्भुत शक्ती आहे.", en: "There is miraculous power in Swami's name." },
  { mr: "तुझी भक्ती स्वामींना जाणवते.", en: "Swami feels your devotion." },
  { mr: "अंतर्मनात स्वामींचे ध्यान ठेव.", en: "Keep Swami in your inner thoughts." },
  { mr: "स्वामी समर्थांची लीला अगाध आहे.", en: "Swami Samarth's play is unfathomable." },
  { mr: "प्रत्येक जप तुला स्वामींच्या जवळ नेतो.", en: "Every chant brings you closer to Swami." },
  { mr: "स्वामींचे नाम सर्व दुःखांचे औषध.", en: "Swami's name is the cure for all sorrows." },
  { mr: "विकल्प सोड, स्वामींवर भरोसा ठेव.", en: "Let go of doubts, trust Swami." },
  { mr: "स्वामी आज तुझ्यासाठी काहीतरी चांगले घडवतील.", en: "Swami will make something good happen for you today." },
  { mr: "तुझ्या जपाला स्वामींची पावती आहे.", en: "Swami acknowledges your chanting." },
  { mr: "स्वामी समर्थ — असो, असो, असो.", en: "Swami Samarth — so be it, so be it, so be it." },
  { mr: "नामात रम, जगात निर्भय.", en: "Absorbed in the name, fearless in the world." },
  { mr: "स्वामींच्या कृपेला मर्यादा नाही.", en: "There is no limit to Swami's grace." },
  { mr: "तुझी साधना तुझे संरक्षण.", en: "Your practice is your protection." },
  { mr: "स्वामी तुमच्या भक्तीने प्रसन्न होतात.", en: "Swami is pleased by your devotion." },
  { mr: "प्रत्येक मालेत स्वामींचे दर्शन.", en: "In every mala, a vision of Swami." },
  { mr: "स्वामींची सेवा हेच जीवन.", en: "Service to Swami is life itself." },
  { mr: "नामजपात आनंद आणि शांती.", en: "Joy and peace in chanting the name." },
  { mr: "स्वामी कृपा अव्याहत वाहते.", en: "Swami's grace flows ceaselessly." },
  { mr: "तुझ्या यशात स्वामींचा हात आहे.", en: "Swami's hand is in your success." },
  { mr: "स्वामी समर्थ — जय जय स्वामी समर्थ.", en: "Swami Samarth — Victory to Swami Samarth." },
  { mr: "नामस्मरणाने मन शुद्ध होते.", en: "The mind is purified by chanting." },
  { mr: "स्वामींचे आशीर्वाद तुझ्या घरावर आहेत.", en: "Swami's blessings are upon your home." },
  { mr: "दुःखात स्वामींचे स्मरण कर.", en: "Remember Swami in times of sorrow." },
  { mr: "सुखात स्वामींचे आभार मान.", en: "In happiness, be grateful to Swami." },
  { mr: "स्वामी तुझा मार्गदर्शक, तुझा रक्षक.", en: "Swami is your guide, your protector." },
  { mr: "एक एक जप ही स्वामींची सेवा.", en: "Each chant is service to Swami." },
  { mr: "स्वामींची कृपा असेल तर कशाला भिऊ?", en: "With Swami's grace, why fear anything?" },
  { mr: "प्रार्थना ही हृदयाची भाषा.", en: "Prayer is the language of the heart." },
  { mr: "स्वामी तुझ्या प्रयत्नांना बळ देतात.", en: "Swami strengthens your efforts." },
  { mr: "नामाच्या स्मरणात दिवस घालव.", en: "Spend the day in remembrance of the name." },
  { mr: "जपाच्या शक्तीवर विश्वास ठेव.", en: "Trust in the power of chanting." },
  { mr: "स्वामी प्रत्येक क्षणी तुझ्याबरोबर.", en: "Swami is with you every moment." },
  { mr: "भक्ताचे दुःख स्वामींचे दुःख.", en: "A devotee's sorrow is Swami's sorrow." },
  { mr: "स्वामी कृपेने अशक्य शक्य होते.", en: "By Swami's grace, the impossible becomes possible." },
  { mr: "नित्य नेम करणारा कधी पडत नाही.", en: "One who practices daily never falls." },
  { mr: "स्वामींचे दर्शन हे सर्वोत्कृष्ट वरदान.", en: "Swami's vision is the highest blessing." },
  { mr: "तुझी श्रद्धा हीच तुझी शक्ती.", en: "Your faith is your strength." },
  { mr: "स्वामी तुझ्या मनातील इच्छा जाणतात.", en: "Swami knows the desires in your heart." },
  { mr: "नामजप करताना मन एकाग्र ठेव.", en: "Keep the mind focused while chanting." },
  { mr: "स्वामींकडे सर्व सोपव.", en: "Surrender everything to Swami." },
  { mr: "आपल्या जपात स्वामींचे बळ मिळते.", en: "We gain Swami's strength through chanting." },
  { mr: "स्वामी समर्थ ही सिद्ध वाणी.", en: "Swami Samarth is the perfected word." },
  { mr: "भक्तासाठी स्वामी सदा तत्पर.", en: "Swami is always ready for the devotee." },
  { mr: "प्रत्येक जपाने पाप नष्ट होतात.", en: "Every chant destroys sins." },
  { mr: "स्वामी कृपेने जीवन सुंदर होते.", en: "Life becomes beautiful by Swami's grace." },
  { mr: "नामाची गोडी लागली की सर्व मिळते.", en: "When you develop a taste for the name, everything follows." },
  { mr: "स्वामींचे नाम हीच खरी दौलत.", en: "Swami's name is the true treasure." },
  { mr: "तुझ्या जपाला स्वामी साक्षी आहेत.", en: "Swami is witness to your chanting." },
  { mr: "स्वामींच्या चरणी लीन हो.", en: "Be humble at Swami's feet." },
  { mr: "नामात विश्वास, जीवनात आनंद.", en: "Faith in the name, joy in life." },
  { mr: "स्वामी तुझ्या सर्व कर्मांचे साक्षी.", en: "Swami is witness to all your deeds." },
  { mr: "जपाच्या मार्गाने मुक्ती मिळते.", en: "Liberation comes through the path of chanting." },
  { mr: "स्वामी भक्ताचे सर्वस्व.", en: "Swami is everything to the devotee." },
  { mr: "प्रत्येक दिवस नव्या उमेदीने जप कर.", en: "Chant every day with renewed hope." },
  { mr: "स्वामींचे प्रेम अनंत आणि अपार.", en: "Swami's love is infinite and boundless." },
  { mr: "नामाचा ध्वनी ब्रह्मांडात गुंजतो.", en: "The sound of the name resonates in the universe." },
  { mr: "स्वामी कृपा ही सर्वात मोठी संपत्ती.", en: "Swami's grace is the greatest wealth." },
  { mr: "जप ही तुझी ढाल, स्वामी तुझी तलवार.", en: "Chanting is your shield, Swami is your sword." },
  { mr: "स्वामींच्या आशीर्वादाने सर्व भय नाहीसे.", en: "By Swami's blessing, all fear vanishes." },
  { mr: "तुझ्या भक्तीचा सुगंध स्वामींपर्यंत पोहोचतो.", en: "The fragrance of your devotion reaches Swami." },
  { mr: "स्वामी म्हणतात — मी तुझ्या पाठीशी आहे.", en: "Swami says — I am behind you." },
  { mr: "नामजपाने शरीर, मन, आत्मा शुद्ध होतो.", en: "Chanting purifies body, mind, and soul." },
  { mr: "स्वामींच्या कृपेने चमत्कार घडतात.", en: "Miracles happen by Swami's grace." },
  { mr: "तुझी साधना हीच तुझी ओळख.", en: "Your practice is your identity." },
  { mr: "स्वामी समर्थ — हे तीन शब्द सर्वशक्तिमान.", en: "Swami Samarth — these three words are omnipotent." },
  { mr: "भक्ती मार्गावर धैर्याने चाल.", en: "Walk the path of devotion with courage." },
  { mr: "स्वामींची कृपादृष्टी तुझ्यावर आहे.", en: "Swami's graceful gaze is upon you." },
  { mr: "प्रत्येक श्वास 'स्वामी समर्थ' ने भरून टाक.", en: "Fill every breath with 'Swami Samarth'." },
  { mr: "तुझ्या जपाने या जगाला ऊर्जा मिळते.", en: "Your chanting gives energy to this world." },
  { mr: "स्वामींबद्दल प्रेम वाढव, सर्व मिळेल.", en: "Increase love for Swami, you will receive all." },
  { mr: "नामाच्या उच्चाराने वातावरण पवित्र होते.", en: "The atmosphere is purified by uttering the name." },
  { mr: "स्वामी भक्ताला कधी रिकाम्या हाताने पाठवत नाहीत.", en: "Swami never sends a devotee away empty-handed." },
  { mr: "आजचा दिवस स्वामींच्या सेवेत घालव.", en: "Spend today in service of Swami." },
  { mr: "जप कर, चिंता सोड.", en: "Chant and let go of worries." },
  { mr: "स्वामी तुझे ऐकतात, बोल मनातले.", en: "Swami listens to you, speak your heart." },
  { mr: "नामजप म्हणजे आत्म्याचे भोजन.", en: "Chanting is food for the soul." },
  { mr: "स्वामी कृपा तुझ्या जीवनाचा कणा.", en: "Swami's grace is the backbone of your life." },
  { mr: "भक्तीत सातत्य ठेव.", en: "Maintain consistency in devotion." },
  { mr: "स्वामी तुझ्या कुटुंबावर कृपा करतात.", en: "Swami bestows grace upon your family." },
  { mr: "प्रत्येक मालेनंतर तू शुद्ध होतोस.", en: "After every mala, you become purer." },
  { mr: "स्वामींचे नाम घेतांना अश्रू येणे हे भाग्य.", en: "Tears while chanting Swami's name is a blessing." },
  { mr: "तुझी भक्ती तुझ्या पिढ्यांना तारेल.", en: "Your devotion will uplift your generations." },
  { mr: "स्वामी तुला कधीही विसरत नाहीत.", en: "Swami never forgets you." },
  { mr: "नामात डूब, जगाचे भान विसर.", en: "Immerse in the name, forget the world." },
  { mr: "स्वामी कृपा अखंड वाहत राहते.", en: "Swami's grace flows uninterrupted." },
  { mr: "तुझी एक माळ लाखों पापांचा नाश करते.", en: "Your one mala destroys millions of sins." },
  { mr: "स्वामी तुला परीक्षेतून बाहेर काढतील.", en: "Swami will bring you out of trials." },
  { mr: "भक्तीने कठीण काळही सोपा होतो.", en: "Difficult times become easy through devotion." },
  { mr: "स्वामी समर्थांचे नाम हेच कवच.", en: "Swami Samarth's name is the armor." },
  { mr: "आपल्या जपाने देवता प्रसन्न होतात.", en: "Our chanting pleases the deities." },
  { mr: "स्वामींसमोर सर्व समान.", en: "Everyone is equal before Swami." },
  { mr: "नामजपात प्रेम ओत.", en: "Pour love into your chanting." },
  { mr: "स्वामींचा मार्ग नम्रतेचा.", en: "Swami's path is of humility." },
  { mr: "तुझा जपसंकल्प स्वामींनी ऐकला.", en: "Swami has heard your chanting resolve." },
  { mr: "प्रत्येक दिवस नव्या आशेचा.", en: "Every day is a day of new hope." },
  { mr: "स्वामींच्या कृपेत सर्व काही सामावले.", en: "Everything is contained in Swami's grace." },
  { mr: "नामजपात थकवा नाही, आनंद आहे.", en: "There is no fatigue in chanting, only joy." },
  { mr: "स्वामी तुला सदैव मार्ग दाखवतात.", en: "Swami always shows you the way." },
  { mr: "तुझे कर्तव्य जप, बाकी स्वामींवर सोड.", en: "Your duty is to chant, leave the rest to Swami." },
  { mr: "स्वामी कृपेने अंधारातही प्रकाश मिळतो.", en: "By Swami's grace, light appears even in darkness." },
  { mr: "भक्ताचे हृदय स्वामींचे निवासस्थान.", en: "The devotee's heart is Swami's dwelling." },
  { mr: "स्वामी म्हणतात — तुझी काळजी मला.", en: "Swami says — I care for you." },
  { mr: "दररोज जपाने तू मोक्षाकडे जातोस.", en: "Daily chanting takes you toward liberation." },
  { mr: "स्वामींचे प्रेम शब्दांत मावत नाही.", en: "Swami's love cannot be contained in words." },
  { mr: "तुझी निष्ठा हीच तुझी शक्ती.", en: "Your dedication is your power." },
  { mr: "स्वामी तुझ्याकडे कृपादृष्टीने पाहतात.", en: "Swami looks at you with grace." },
  { mr: "जप करताना ईश्वर तुझ्यात प्रकट होतो.", en: "God manifests in you while chanting." },
  { mr: "स्वामी कृपा ही सूर्यप्रकाशासारखी.", en: "Swami's grace is like sunlight." },
  { mr: "तुझ्या जपाने कुटुंबाचे कल्याण होते.", en: "Your chanting brings welfare to your family." },
  { mr: "स्वामींचे अस्तित्व प्रत्येक कणात आहे.", en: "Swami's presence is in every particle." },
  { mr: "भक्तीचा मार्ग शांत आणि सुंदर.", en: "The path of devotion is peaceful and beautiful." },
  { mr: "स्वामी कृपेने तुझे जीवन बदलेल.", en: "By Swami's grace, your life will change." },
  { mr: "प्रत्येक जपाने तुझे आभामंडल शुद्ध होते.", en: "Every chant purifies your aura." },
  { mr: "स्वामी तुला कधीच एकटे सोडत नाहीत.", en: "Swami never leaves you alone." },
  { mr: "नामजपात चमत्काराची शक्ती आहे.", en: "The power of miracles is in chanting." },
  { mr: "तुझ्या जपाने पृथ्वीचे कल्याण होते.", en: "Your chanting benefits the earth." },
  { mr: "स्वामी समर्थ — शरण आलो.", en: "Swami Samarth — I have taken refuge." },
  { mr: "भय सोड, स्वामी तुझे आहेत.", en: "Let go of fear, Swami is yours." },
  { mr: "जपाने मनाला शांती, आत्म्याला तृप्ती.", en: "Chanting brings peace to mind, satisfaction to soul." },
  { mr: "स्वामींचे नाम हीच तुझी प्रार्थना.", en: "Swami's name is your prayer." },
  { mr: "तुझ्या अंतरात स्वामी बसले आहेत.", en: "Swami sits within your heart." },
  { mr: "साधनेत सातत्य म्हणजे यश.", en: "Consistency in practice means success." },
  { mr: "स्वामींच्या नामात सर्व वेदांचा सार.", en: "In Swami's name lies the essence of all Vedas." },
  { mr: "तुझी प्रत्येक माळ स्वामींना प्रिय.", en: "Every mala of yours is dear to Swami." },
  { mr: "स्वामी म्हणतात — घाबरू नकोस, मी आहे.", en: "Swami says — Don't be afraid, I am here." },
  { mr: "भक्तीचा अनुभव शब्दांच्या पलीकडे.", en: "The experience of devotion is beyond words." },
  { mr: "स्वामी तुझ्या सर्व प्रश्नांची उत्तरे जाणतात.", en: "Swami knows the answers to all your questions." },
  { mr: "नामजपाने रोग दूर होतात.", en: "Chanting cures diseases." },
  { mr: "स्वामींचे चरण हीच तुझी गती.", en: "Swami's feet are your destination." },
  { mr: "तुझ्या श्रद्धेमुळे स्वामी तुला निवडतात.", en: "Because of your faith, Swami chooses you." },
  { mr: "जपाच्या ध्वनीत दिव्यत्व आहे.", en: "There is divinity in the sound of chanting." },
  { mr: "स्वामी तुझ्या प्रत्येक हाकेला प्रतिसाद देतात.", en: "Swami responds to your every call." },
  { mr: "भक्ती हीच सर्वोत्तम प्रार्थना.", en: "Devotion is the highest prayer." },
  { mr: "स्वामींच्या कृपेने सर्व संकटे दूर.", en: "By Swami's grace, all troubles are removed." },
  { mr: "तुझ्या जपाने तुझे नशीब बदलते.", en: "Your chanting changes your destiny." },
  { mr: "स्वामी साक्षात परब्रह्म.", en: "Swami is the Supreme Being incarnate." },
  { mr: "प्रत्येक दिवशी एक पाऊल पुढे.", en: "One step forward every day." },
  { mr: "स्वामी कृपा अमृतासारखी.", en: "Swami's grace is like nectar." },
  { mr: "तुझ्या जपाने देवालय पवित्र होते.", en: "Your chanting sanctifies the temple." },
  { mr: "स्वामी तुझ्या भक्तीवर प्रेम करतात.", en: "Swami loves your devotion." },
  { mr: "नामस्मरण ही आत्म्याची उड्डाण.", en: "Remembering the name is the soul's flight." },
  { mr: "स्वामींच्या कृपेने तू धन्य आहेस.", en: "By Swami's grace, you are blessed." },
  { mr: "तुझी भक्ती तुझे कवच आणि ढाल.", en: "Your devotion is your armor and shield." },
  { mr: "स्वामी तुझ्यासाठी सदैव उपलब्ध.", en: "Swami is always available for you." },
  { mr: "जपात एकाग्रता म्हणजे स्वामी दर्शन.", en: "Concentration in chanting means Swami's vision." },
  { mr: "स्वामींच्या कृपेत सागरासारखी गहिरता.", en: "Swami's grace has ocean-like depth." },
  { mr: "तुझ्या मनाला स्वामींच्या नामाने शांत कर.", en: "Calm your mind with Swami's name." },
  { mr: "भक्तीने जग जिंकता येते.", en: "The world can be conquered through devotion." },
  { mr: "स्वामींचे नाम ही सर्वात मोठी शक्ती.", en: "Swami's name is the greatest power." },
  { mr: "तुझ्या जपाने पूर्वजही तृप्त होतात.", en: "Your chanting satisfies even ancestors." },
  { mr: "स्वामी तुझ्या प्रगतीवर नजर ठेवतात.", en: "Swami watches over your progress." },
  { mr: "नामजपात विश्रांती आणि शक्ती दोन्ही.", en: "Both rest and strength are in chanting." },
  { mr: "स्वामींच्या कृपेने विजय निश्चित.", en: "Victory is certain by Swami's grace." },
  { mr: "तुझ्या भक्तीचे फळ तुला मिळेलच.", en: "You will surely receive the fruit of your devotion." },
  { mr: "स्वामी तुला आधार देतात, तू पड.", en: "Swami supports you, don't fall." },
  { mr: "प्रत्येक जपात स्वामींची ऊर्जा.", en: "Swami's energy in every chant." },
  { mr: "स्वामींचे प्रेम अटळ आणि शाश्वत.", en: "Swami's love is unfailing and eternal." },
  { mr: "तुझ्या हृदयातील स्वामी तुला बोलावतात.", en: "The Swami in your heart calls you." },
  { mr: "जपाने जीवनात सुसंवाद येतो.", en: "Chanting brings harmony to life." },
  { mr: "स्वामींच्या आज्ञेत राहणे हेच भक्तीचे लक्षण.", en: "Obeying Swami is the hallmark of devotion." },
  { mr: "तुझ्या जपामुळे इतरांनाही प्रेरणा मिळते.", en: "Your chanting inspires others too." },
  { mr: "स्वामी समर्थ — अनंत कोटी ब्रह्मांड नायक.", en: "Swami Samarth — Lord of infinite universes." },
  { mr: "भक्तीचा दीप सदा तेवत ठेव.", en: "Keep the lamp of devotion always burning." },
  { mr: "स्वामींच्या मार्गावर चालणे हेच सुख.", en: "Walking on Swami's path is true happiness." },
  { mr: "तुझ्या जपाने आत्मविश्वास वाढतो.", en: "Your chanting increases self-confidence." },
  { mr: "स्वामी तुझ्या स्वप्नांना साकार करतील.", en: "Swami will manifest your dreams." },
  { mr: "प्रत्येक 'स्वामी समर्थ' ने तू बळकट होतोस.", en: "With every 'Swami Samarth' you grow stronger." },
  { mr: "स्वामींची कृपा तुझ्या अपेक्षेपेक्षा मोठी.", en: "Swami's grace is bigger than your expectations." },
  { mr: "नामजप ही सर्वोत्तम साधना.", en: "Chanting the name is the best practice." },
  { mr: "स्वामींच्या कृपेने तू आज इथे आहेस.", en: "By Swami's grace, you are here today." },
  { mr: "तुझ्या प्रत्येक जपात प्रेम भर.", en: "Fill every chant of yours with love." },
  { mr: "स्वामी तुझ्या कष्टांचे चीज करतील.", en: "Swami will reward your efforts." },
  { mr: "नामजपात शक्ती, शांती आणि संतोष.", en: "Power, peace and contentment are in chanting." },
  { mr: "स्वामींचे प्रेम ही सर्वात शुद्ध भावना.", en: "Swami's love is the purest emotion." },
  { mr: "तुझी प्रत्येक माळ एक पवित्र यज्ञ.", en: "Your every mala is a sacred offering." },
  { mr: "स्वामी तुझ्या जीवनाचे रक्षण करतात.", en: "Swami protects your life." },
  { mr: "जपाच्या सवयीने जीवन बदलते.", en: "The habit of chanting transforms life." },
  { mr: "स्वामींच्या नामात अपार शक्ती.", en: "Immense power in Swami's name." },
  { mr: "तुझ्या भक्तीने स्वामी प्रसन्न आहेत.", en: "Swami is pleased with your devotion." },
  { mr: "प्रत्येक सकाळ स्वामींची कृपा.", en: "Every morning is Swami's blessing." },
  { mr: "स्वामींच्या स्मरणात दिवस सुरू कर.", en: "Start the day with remembrance of Swami." },
  { mr: "तुझ्या जपाचे सामर्थ्य अगणित.", en: "The power of your chanting is immeasurable." },
  { mr: "स्वामी तुला शक्ती देतात, बळ देतात.", en: "Swami gives you power, gives you strength." },
  { mr: "नामजपात आत्म्याचा अनुभव.", en: "In chanting, experience the soul." },
  { mr: "स्वामींचे नाम तुझ्या ओठांवर नाचो.", en: "May Swami's name dance on your lips." },
  { mr: "भक्ती आणि श्रद्धा — हेच दोन पंख.", en: "Devotion and faith — these are the two wings." },
  { mr: "स्वामी कृपेने तुझ्या दिवसाला आशीर्वाद.", en: "Swami's grace blesses your day." },
  { mr: "जपाने तुझे मन शांत, तुझे हृदय तृप्त.", en: "Chanting calms your mind, satisfies your heart." },
  { mr: "स्वामींचे चरण म्हणजे स्वर्ग.", en: "Swami's feet are heaven." },
  { mr: "तुझ्या भक्तीच्या आनंदात स्वामी सामील.", en: "Swami participates in the joy of your devotion." },
  { mr: "नामजपाने कर्मबंधन तुटते.", en: "Chanting breaks the bondage of karma." },
  { mr: "स्वामींचे मार्गदर्शन हीच तुझी दिशा.", en: "Swami's guidance is your direction." },
  { mr: "प्रत्येक जपात स्वामींचा स्पर्श.", en: "Swami's touch in every chant." },
  { mr: "स्वामी कृपा सर्व ऋतूंत समान.", en: "Swami's grace is same in all seasons." },
  { mr: "तुझ्या जपसंकल्पाला स्वामींचा आधार.", en: "Swami supports your chanting resolve." },
  { mr: "भक्तीत जे मिळते ते कुठेही मिळत नाही.", en: "What devotion provides, nothing else can." },
  { mr: "स्वामींसाठी तुझा प्रत्येक प्रयत्न मोलाचा.", en: "Every effort of yours is precious to Swami." },
  { mr: "नामजपात तुझी सर्व उत्तरे.", en: "All your answers are in chanting." },
  { mr: "स्वामी तुझ्या जीवनात प्रकाश आहेत.", en: "Swami is the light in your life." },
  { mr: "जपसंकल्प पूर्ण कर — स्वामी बळ देतील.", en: "Complete your chanting resolve — Swami will give strength." },
  { mr: "स्वामींच्या नामाने तुझा दिवस शुभ.", en: "Your day is auspicious with Swami's name." },
  { mr: "भक्ताचे प्रेम स्वामींपर्यंत पोहोचतेच.", en: "A devotee's love surely reaches Swami." },
  { mr: "स्वामी कृपेने प्रत्येक क्षण सुंदर.", en: "Every moment is beautiful by Swami's grace." },
  { mr: "तुझ्या जपात ईश्वरी शक्ती.", en: "Divine power in your chanting." },
  { mr: "स्वामींचे नाम सर्वत्र गुंजू दे.", en: "Let Swami's name resound everywhere." },
  { mr: "प्रत्येक माळ एक पाऊल स्वामींकडे.", en: "Every mala is a step toward Swami." },
  { mr: "स्वामी कृपा ही तुझी सर्वात मोठी जमापुंजी.", en: "Swami's grace is your greatest asset." },
  { mr: "तुझ्या जपाने जग सुंदर होते.", en: "Your chanting makes the world beautiful." },
  { mr: "स्वामी तुझ्यासाठी सर्वोत्तम घडवतील.", en: "Swami will arrange the best for you." },
  { mr: "नामात ताकद, नामात प्रेम.", en: "Strength in the name, love in the name." },
  { mr: "स्वामींचे आशीर्वाद तुझ्यासोबत सदैव.", en: "Swami's blessings are always with you." },
  { mr: "भक्ती शिका, प्रेम शिका, क्षमा शिका.", en: "Learn devotion, learn love, learn forgiveness." },
  { mr: "स्वामी तुझ्या चांगुलपणाचे कौतुक करतात.", en: "Swami appreciates your goodness." },
  { mr: "नामजपाचे फळ अनंत काळ टिकते.", en: "The fruit of chanting lasts for eternity." },
  { mr: "स्वामी कृपेने तुला सर्व शक्य.", en: "Everything is possible for you by Swami's grace." },
  { mr: "तुझी प्रत्येक प्रार्थना ऐकली जाते.", en: "Every prayer of yours is heard." },
  { mr: "स्वामींच्या चरणी शरण ये.", en: "Take refuge at Swami's feet." },
  { mr: "जपाने तुझ्या जीवनात चमत्कार.", en: "Miracles in your life through chanting." },
  { mr: "स्वामी तुझ्या प्रत्येक दुःखावर फुंकर घालतात.", en: "Swami soothes every pain of yours." },
  { mr: "नामजप तुझे परम कर्तव्य.", en: "Chanting is your supreme duty." },
  { mr: "स्वामींच्या कृपेत तुझे कल्याण.", en: "Your welfare is in Swami's grace." },
  { mr: "प्रत्येक दिवस जपासाठी — प्रत्येक जप स्वामींसाठी.", en: "Every day for chanting — every chant for Swami." },
  { mr: "स्वामींचे प्रेम ही तुझी सर्वात मोठी ताकद.", en: "Swami's love is your greatest strength." },
  { mr: "भक्तीत सातत्य राखणारा यशस्वी होतो.", en: "One who maintains consistency in devotion succeeds." },
  { mr: "स्वामी म्हणतात — चिंता नको, जप कर.", en: "Swami says — Don't worry, just chant." },
  { mr: "तुझ्या जपसंकल्पात स्वामींचा आशीर्वाद.", en: "Swami's blessing is in your chanting resolve." },
  { mr: "नामजप सर्वांसाठी समान आणि सुलभ.", en: "Chanting is equal and easy for everyone." },
  { mr: "स्वामी कृपेने तुझे भविष्य उज्ज्वल.", en: "Your future is bright by Swami's grace." },
  { mr: "तुझ्या भक्तीने स्वर्गाचे दार उघडते.", en: "Your devotion opens the door to heaven." },
  { mr: "स्वामींचे नाम तुझे सर्वकाळ रक्षण करो.", en: "May Swami's name protect you at all times." },
  { mr: "जपाने तुझे सर्व दोष नष्ट होतात.", en: "Chanting destroys all your flaws." },
  { mr: "स्वामी तुला अनंत प्रेम करतात.", en: "Swami loves you infinitely." },
  { mr: "प्रत्येक नवा दिवस स्वामींच्या कृपेने.", en: "Every new day is by Swami's grace." },
  { mr: "तुझ्या जपाचा आवाज स्वर्गापर्यंत पोहोचतो.", en: "The sound of your chanting reaches heaven." },
  { mr: "स्वामी म्हणतात — तू माझा, मी तुझा.", en: "Swami says — You are mine, I am yours." },
  { mr: "नामजपात विलंब नको, आज सुरू कर.", en: "Don't delay chanting, start today." },
  { mr: "स्वामींचे आशीर्वाद सर्व अडचणी दूर करतात.", en: "Swami's blessings remove all difficulties." },
  { mr: "तुझी भक्ती ही तुझी ओळख.", en: "Your devotion is your identity." },
  { mr: "स्वामी कृपा सर्वांना समान.", en: "Swami's grace is equal for all." },
  { mr: "प्रत्येक जपात तू नव्याने जन्म घेतोस.", en: "You are reborn with every chant." },
  { mr: "स्वामींच्या आशीर्वादाने सर्व मंगल.", en: "Everything is auspicious with Swami's blessings." },
  { mr: "नामजप — सर्वांत सोपी आणि सर्वांत शक्तिशाली साधना.", en: "Chanting — the easiest and most powerful practice." },
  { mr: "स्वामी तुझ्या प्रत्येक कृतीत आहेत.", en: "Swami is in your every action." },
  { mr: "तुझ्या जपाने स्वामी तुझ्याजवळ येतात.", en: "Your chanting draws Swami closer to you." },
  { mr: "भक्तीने अहंकार गळतो.", en: "Ego dissolves through devotion." },
  { mr: "स्वामी कृपेने तू सदैव सुरक्षित.", en: "You are always safe by Swami's grace." },
  { mr: "प्रत्येक सकाळ स्वामींच्या नामाने सुरू कर.", en: "Start every morning with Swami's name." },
  { mr: "स्वामींचे नाम हीच तुझी ताकद आणि शक्ती.", en: "Swami's name is your power and strength." },
  { mr: "तुझा जप स्वामींना सर्वाधिक प्रिय.", en: "Your chanting is most dear to Swami." },
  { mr: "स्वामी तुझ्या हृदयात सदैव जागृत.", en: "Swami is always awake in your heart." },
  { mr: "भक्तीचे फूल स्वामींना अर्पण कर.", en: "Offer the flower of devotion to Swami." },
  { mr: "स्वामी कृपा — अखंड, अपार, अनंत.", en: "Swami's grace — unbroken, boundless, infinite." },
  { mr: "तुझ्यासारख्या भक्तांमुळेच स्वामी प्रसन्न.", en: "Swami is pleased because of devotees like you." },
  { mr: "नामजपात तुझे सर्व दुःख विरतात.", en: "All your sorrows dissolve in chanting." },
  { mr: "स्वामी तुझ्याशी बोलतात — ऐकण्याची कला शिक.", en: "Swami speaks to you — learn the art of listening." },
  { mr: "प्रत्येक माळेत हजार आशीर्वाद.", en: "A thousand blessings in every mala." },
  { mr: "स्वामी तुझे जगणे सुंदर करतील.", en: "Swami will make your living beautiful." },
  { mr: "जपात मन लाव, स्वामी तुझ्याजवळ.", en: "Focus the mind in chanting, Swami is near you." },
  { mr: "स्वामींचे नाव तुझ्या ओठांवर कायम राहो.", en: "May Swami's name remain forever on your lips." },
  { mr: "तुझ्या प्रत्येक जपात स्वामींचे हास्य.", en: "Swami's smile in your every chant." },
  { mr: "भक्ती ही अंतःकरणाची सर्वोत्तम अभिव्यक्ती.", en: "Devotion is the finest expression of the heart." },
  { mr: "स्वामी तुझ्या प्रयत्नांची कदर करतात.", en: "Swami values your efforts." },
  { mr: "नामजपात तुझे मोक्षाचे बीज.", en: "The seed of liberation is in your chanting." },
  { mr: "स्वामी कृपा तुझी सदैव साथीदार.", en: "Swami's grace is your constant companion." },
  { mr: "तुझ्या जपसंकल्पात यश निश्चित.", en: "Success is certain in your chanting resolve." },
  { mr: "स्वामींच्या नामात अनंत सामर्थ्य.", en: "Infinite power in Swami's name." },
  { mr: "भक्ती + श्रद्धा + सातत्य = स्वामी कृपा.", en: "Devotion + Faith + Consistency = Swami's grace." },
  { mr: "स्वामी तुझ्या जीवनाचे सारथी.", en: "Swami is the charioteer of your life." },
  { mr: "प्रत्येक जपात तुझे आरोग्य सुधारते.", en: "Your health improves with every chant." },
  { mr: "स्वामी म्हणतात — तू पुढे चल, मी मागे आहे.", en: "Swami says — Walk ahead, I am behind you." },
  { mr: "नामजपात सर्व शास्त्रांचे ज्ञान.", en: "All scriptural knowledge is in chanting." },
  { mr: "स्वामी तुला आणखी उंचीवर नेतील.", en: "Swami will take you to greater heights." },
  { mr: "तुझी प्रत्येक माळ स्वामींना पुष्पांजली.", en: "Each mala of yours is a floral offering to Swami." },
  { mr: "स्वामी कृपेने तू अजिंक्य.", en: "You are invincible by Swami's grace." },
  { mr: "भक्तीने सर्व बंधने तुटतात.", en: "All bonds break through devotion." },
  { mr: "स्वामींच्या आशीर्वादाने तुझे कुटुंब सुखी.", en: "Your family is happy with Swami's blessings." },
  { mr: "नामजपात प्रत्येक क्षण मौल्यवान.", en: "Every moment in chanting is precious." },
  { mr: "स्वामी तुझ्या यशाचे कारण.", en: "Swami is the cause of your success." },
  { mr: "तुझ्या जपात स्वामींचा प्रकाश.", en: "Swami's light in your chanting." },
  { mr: "प्रत्येक रात्री स्वामींना धन्यवाद दे.", en: "Thank Swami every night." },
  { mr: "स्वामी कृपेने तुझे सर्व चिंतन सकारात्मक.", en: "All your thoughts are positive by Swami's grace." },
  { mr: "नामजप — शांतीचा सागर.", en: "Chanting — an ocean of peace." },
  { mr: "स्वामींच्या चरणी सदा नमन.", en: "Always bowing at Swami's feet." },
  { mr: "तुझी भक्ती ही जगाला प्रेरणा.", en: "Your devotion inspires the world." },
  { mr: "स्वामींच्या प्रेमात सर्वस्व आहे.", en: "Everything is in Swami's love." },
  { mr: "प्रत्येक जपात तुझ्यावरचा स्वामींचा आशीर्वाद.", en: "Swami's blessing upon you in every chant." },
  { mr: "जय जय स्वामी समर्थ!", en: "Victory, Victory to Swami Samarth!" },
  { mr: "तुझे ६ लाख जप पूर्ण होतील — स्वामी कृपा!", en: "Your 6 lakh jap will be complete — Swami's grace!" },
  { mr: "स्वामी तुझ्या संकल्पाला बळ देतात.", en: "Swami empowers your resolve." },
  { mr: "तुझा प्रवास सुंदर आहे — चालत रहा.", en: "Your journey is beautiful — keep walking." },
  { mr: "स्वामी समर्थ — तुझ्या जीवनाचा अर्थ.", en: "Swami Samarth — the meaning of your life." },
  { mr: "तुझ्या संकल्पात स्वामींची शक्ती.", en: "Swami's power in your resolve." },
  { mr: "आज रात्री शांत झोप — स्वामी रक्षण.", en: "Sleep peacefully tonight — Swami protects." },
  { mr: "तुझा आजचा जप स्वामींना समर्पित.", en: "Today's chanting is dedicated to Swami." },
  { mr: "स्वामी कृपेने तुझे सर्व स्वप्न पूर्ण.", en: "All your dreams fulfilled by Swami's grace." },
  { mr: "तुझ्या प्रवासात स्वामी तुझे ध्येय पूर्ण करतील.", en: "In your journey, Swami will fulfill your goal." }
];

// Special anniversary messages
const ANNIVERSARY_MESSAGES = {
  365: {
    mr: "एक वर्ष पूर्ण! स्वामी समर्थांचा आशीर्वाद तुझ्यावर सदैव आहे. तुझी भक्ती अखंड राहो!",
    en: "One year complete! Swami Samarth's blessings are always upon you. May your devotion remain unbroken!"
  },
  730: {
    mr: "दोन वर्षे पूर्ण! तुझी साधना अद्भुत आहे. स्वामी तुझ्यावर अत्यंत प्रसन्न आहेत!",
    en: "Two years complete! Your practice is extraordinary. Swami is immensely pleased with you!"
  },
  1095: {
    mr: "तीन वर्षे पूर्ण! ६ लाख जपांचा संकल्प पूर्ण! स्वामी समर्थांचे परम आशीर्वाद तुझ्यावर आहेत. तू धन्य आहेस!",
    en: "Three years complete! 6 lakh jap resolve fulfilled! Swami Samarth's supreme blessings are upon you. You are truly blessed!"
  }
};

// Milestone celebration messages
const MILESTONE_MESSAGES = {
  10000: {
    mr: "स्वामी समर्थ प्रसन्न आहेत! तू १०,००० जपांचा टप्पा गाठलास!",
    en: "Swami Samarth is pleased! You have reached 10,000 jap!",
    badge: "🕉️",
    title: "Naam Sevak"
  },
  108000: {
    mr: "स्वामी समर्थ प्रसन्न आहेत! तू १,०८,००० जपांचा पवित्र टप्पा गाठलास!",
    en: "Swami Samarth is pleased! You have reached the sacred milestone of 1,08,000 jap!",
    badge: "🪷",
    title: "Mala Master"
  },
  200000: {
    mr: "स्वामी समर्थ प्रसन्न आहेत! तू २,००,००० जपांचा टप्पा गाठलास!",
    en: "Swami Samarth is pleased! You have reached 2,00,000 jap!",
    badge: "🔱",
    title: "Sadhana Warrior"
  },
  300000: {
    mr: "स्वामी समर्थ प्रसन्न आहेत! तू ३,००,००० जपांचा अर्धा मार्ग पार केलास!",
    en: "Swami Samarth is pleased! You have crossed the halfway mark of 3,00,000 jap!",
    badge: "⚡",
    title: "Half Way Hero"
  },
  500000: {
    mr: "स्वामी समर्थांचा विशेष आशीर्वाद! ५,००,००० जप पूर्ण — तू जवळ आहेस!",
    en: "Swami Samarth's special blessing! 5,00,000 jap complete — you are close!",
    badge: "👑",
    title: "Jap Emperor"
  },
  600000: {
    mr: "जय जय स्वामी समर्थ! ६,००,००० जपांचा महासंकल्प पूर्ण! तू धन्य आहेस!",
    en: "Victory to Swami Samarth! The grand resolve of 6,00,000 jap is complete! You are truly blessed!",
    badge: "🏆",
    title: "Sankalpa Siddha"
  }
};

// Streak milestone messages
const STREAK_MESSAGES = {
  7: { mr: "७ दिवसांची अखंड माळ! शाब्बास!", en: "7 day unbroken streak! Well done!" },
  30: { mr: "३० दिवसांची अखंड साधना! अद्भुत!", en: "30 day unbroken practice! Amazing!" },
  100: { mr: "१०० दिवसांची अखंड साधना! स्वामी प्रसन्न!", en: "100 day unbroken practice! Swami is pleased!" },
  365: { mr: "३६५ दिवसांची अखंड साधना! एक वर्ष! तू खरा भक्त!", en: "365 day unbroken practice! One year! You are a true devotee!" }
};
